spring:
  data:
    mongodb:
      username: budgt
      password: '&#Uvbrf&6hnv*Z5H'
      host: budgt-mongodb
      database: budgt
      port: 27017
server:
  port: 1331
eureka:
  client:
      serviceUrl:
        defaultZone: http://budgt-registry-service:1340/eureka
