spring:
  data:
    mongodb:
      username: budgt
      password: '&#Uvbrf&6hnv*Z5H'
      host: budgt-mongodb
      database: budgt
      port: 27017
server:
  servlet:
    context-path: /uaa
  port: 1330
