zuul:
  routes:
    ui:
      url: http://budgt-frontend:1380/
    category-service:
      path: /api/category-service/**
      serviceId: category-service
      stripPrefix: true 
    auth-service:
      path: /uaa/**
      serviceId: auth-service
      stripPrefix: true
      sensitiveHeaders:
    account-service:
      path: /accounts/**
      serviceId: account-service
      stripPrefix: false
      sensitiveHeaders:
spring:
  data:
    mongodb:
      username: budgt
      password: '&#Uvbrf&6hnv*Z5H'
      host: budgt-mongodb
      database: budgt
      port: 27017
