zuul:
  routes:
    ui:
      url: http://budgt-frontend:1380/
    category-service:
      path: /api/category-service/**
      serviceId: category-service
      stripPrefix: true 
      sensitiveHeaders:
    auth-service:
      path: /api/uaa/**
      serviceId: auth-service
      stripPrefix: true
      sensitiveHeaders:
    account-service:
      path: /api/account-service/**
      serviceId: account-service
      stripPrefix: true
      sensitiveHeaders:
    bank-account-service:
      path: /api/bank-account-service/**
      serviceId: bank-sccount-service
      stripPrefix: true 
      sensitiveHeaders:

spring:
  data:
    mongodb:
      username: budgt
      password: '&#Uvbrf&6hnv*Z5H'
      host: budgt-mongodb
      database: budgt
      port: 27017
